language: php
php:
  - "7.4"

addons:
  chrome: stable

install:
  - composer install --prefer-dist
  - cd vendor/symfony/panther/chromedriver-bin && ./update.sh && cd ../../../..
  - composer setup

script:
  - composer ci

cache:
  directories:
    - $HOME/.composer/cache/files
