language: php
php:
  - "7.4"

services:
  - docker

install:
  - composer install --prefer-dist

script:
  - composer ci
  - ./build/build.sh
  - ./build/test_image_exists.sh
  - composer test-integration

cache:
  directories:
    - $HOME/.composer/cache/files
