parameters:
  application_name: Basil Runner

services:
  _defaults:
    autowire: true
    autoconfigure: true

  webignition\BasilRunner\:
    resource: '../src'

  webignition\BasilRunner\Command\RunCommand:
    public: true

  webignition\BasilRunner\ApplicationConfiguration:
    arguments:
      $name: '%application_name%'
    public: true

  Symfony\Component\Console\Application:
    public: true

  webignition\BasilLoader\TestSuiteLoader:
    factory: ['webignition\BasilLoader\TestSuiteLoader', 'createLoader']

  webignition\BasilLoader\TestLoader:
    factory: ['webignition\BasilLoader\TestLoader', 'createLoader']

  webignition\BasilCompiler\Compiler:
    factory: ['webignition\BasilCompiler\Compiler', 'create']

  webignition\BasilCompiler\ExternalVariableIdentifiers:
    arguments:
      $domNavigatorCrawlerName: '$this-navigator'
      $environmentVariableArrayName: '$_ENV'
      $pantherClientName: 'self::$client'
      $pantherCrawlerName: 'self::$crawler'
      $phpUnitTestCaseName: '$this'
      $webDriverElementInspectorName: 'self::$inspector'
      $webDriverElementMutatorName: 'self::$mutator'