parameters:
  application_name: Basil Runner

services:
  _defaults:
    autowire: true
    autoconfigure: true

  webignition\BasilRunner\Command\GenerateCommand:
    public: true

  webignition\BasilRunner\Services\TestGenerator:
    public: true
